# Generated by Django 2.2.6 on 2019-11-21 12:45

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('anything', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FieldTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('field_text', models.CharField(max_length=50)),
                ('freq', models.CharField(max_length=50)),
                ('posting', models.CharField(max_length=2000)),
                ('c_posting', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultSize', models.IntegerField(default=0)),
                ('ranking', jsonfield.fields.JSONField()),
                ('query', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='search.BookQuery')),
            ],
        ),
    ]
